//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Baselines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Baselines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.Baselines", typeof(Baselines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,7.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,7.25000000
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,6.25000000
        ///14,39,12871,12873.75,12869.5,12872.75,333,5.75000000
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,5.80000000
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,6.12500000
        ///14,42,12866,12870.75,12866,12870.25,374,5.96428571
        ///14,43,12869.5,12883,12869.5,12877.25,1369,6.90625000
        ///14,44,12877.75,12878.25,12866.25,12868.75,1047,7.47222222
        ///14,45,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtrBaseline {
            get {
                return ResourceManager.GetString("AtrBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866.00,12870.75,1068,12870.75000000,12870.75000000,12870.75000000
        ///14,37,12871.25,12871.50,12864.75,12869.50,0427,12871.37500000,12870.12500000,12868.87500000
        ///14,38,12869.25,12871.75,12867.50,12871.25,0414,12871.97196014,12870.50000000,12869.02803986
        ///14,39,12871.00,12873.75,12869.50,12872.75,0333,12873.39099200,12871.06250000,12868.73400800
        ///14,40,12872.75,12873.75,12867.75,12870.50,0378,12873.08072758,12870.95000000,12868.81927242
        ///14,41,12870.25,12872.25,12864.50,12865.75,0601, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BollingerBandsBaseline {
            get {
                return ResourceManager.GetString("BollingerBandsBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12860.25,12860.5,12853.75,12858.5,427,0
        ///14,37,12858.25,12860.75,12856.5,12860.25,414,66.6666666666667
        ///14,38,12860,12862.75,12858.5,12861.75,333,100
        ///14,39,12861.75,12862.75,12856.75,12859.5,378,21.2765957446841
        ///14,40,12859.25,12861.25,12853.5,12854.75,601,-109.250398724081
        ///14,41,12855,12859.75,12855,12859.25,374,-33.6917562722946
        ///14,42,12858.5,12872,12858.5,12866.25,1369,189.322493225045
        ///14,43,12866.75,12867.25,12855.25,12857.75,1047,13.5717560753043
        ///14,44,12858.25,12859.75,12850,12856.5,881,-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CciBaseline {
            get {
                return ResourceManager.GetString("CciBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,12870.33677686
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,12870.61100676
        ///14,39,12871,12873.75,12869.5,12872.75,333,12871.31157366
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,12871.08429783
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,12869.34259094
        ///14,42,12866,12870.75,12866,12870.25,374,12869.54549489
        ///14,43,12869.5,12883,12869.5,12877.25,1369,12872.01866217
        ///14,44,12877.75,12878.25,12866.25,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemaBaseline {
            get {
                return ResourceManager.GetString("DemaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,12870.52272727
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,12870.65495868
        ///14,39,12871,12873.75,12869.5,12872.75,333,12871.03587528
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,12870.93844341
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,12869.99509006
        ///14,42,12866,12870.75,12866,12870.25,374,12870.04143733
        ///14,43,12869.5,12883,12869.5,12877.25,1369,12871.35208508
        ///14,44,12877.75,12878.25,12866.25,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmaBaseline {
            get {
                return ResourceManager.GetString("EmaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,12869.50000000
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,12871.25000000
        ///14,39,12871,12873.75,12869.5,12872.75,333,12872.75000000
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,12870.50000000
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,12865.75000000
        ///14,42,12866,12870.75,12866,12870.25,374,12870.25000000
        ///14,43,12869.5,12883,12869.5,12877.25,1369,12877.25000000
        ///14,44,12877.75,12878.25,12866.25,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KamaBaseline {
            get {
                return ResourceManager.GetString("KamaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12860.25,12860.5,12853.75,12858.5,427,12867.7083333333,12857.5833333333,12847.4583333333
        ///14,37,12858.25,12860.75,12856.5,12860.25,414,12866.625,12858.375,12850.125
        ///14,38,12860,12862.75,12858.5,12861.75,333,12866.875,12859.25,12851.625
        ///14,39,12861.75,12862.75,12856.75,12859.5,378,12867.3229166667,12859.3541666667,12851.3854166667
        ///14,40,12859.25,12861.25,12853.5,12854.75,601,12867.4833333333,12858.7833333333,12850.0833333333
        ///14,41,12855,12859.75,12855,12859.25,374,12867.0902777778,12858.6527777778, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeltnerChannelBaseline {
            get {
                return ResourceManager.GetString("KeltnerChannelBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866.00,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.50,12864.75,12869.50,0427,12869.50000000
        ///14,38,12869.25,12871.75,12867.50,12871.25,0414,12870.75000000
        ///14,39,12871.00,12873.75,12869.50,12872.75,0333,12872.22500000
        ///14,40,12872.75,12873.75,12867.75,12870.50,0378,12871.50000000
        ///14,41,12870.25,12872.25,12864.50,12865.75,0601,12868.61904762
        ///14,42,12866.00,12870.75,12866.00,12870.25,0374,12869.06250000
        ///14,43,12869.50,12883.00,12869.50,12877.25,1369,12872.27083333
        ///14,44,12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LinRegBaseline {
            get {
                return ResourceManager.GetString("LinRegBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,0,0,0
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,-0.07102273,-0.03551136,-0.03551136
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,-0.02082257,-0.02816697,0.0073444
        ///14,39,12871,12873.75,12869.5,12872.75,333,0.10081669,0.03632486,0.06449183
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,0.05776714,0.047046,0.01072114
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,-0.24425167,-0.09860283,-0.14564884
        ///14,42,12866,12870.75,12866,12870.25,374,-0.19923669,-0.14891976,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MacdBaseline {
            get {
                return ResourceManager.GetString("MacdBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,0,0
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,0,0
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,0,0
        ///14,39,12871,12873.75,12869.5,12872.75,333,0,0
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,0,0
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,0,0
        ///14,42,12866,12870.75,12866,12870.25,374,0,0
        ///14,43,12869.5,12883,12869.5,12877.25,1369,0,0
        ///14,44,12877.75,12878.25,12866.25,12868.75,1047,0,50
        ///14,45,12869.25,12870.75,12861,12867.5,881,45.03816794,47.51908397
        ///14,46 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsiBaseline {
            get {
                return ResourceManager.GetString("RsiBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,1287.07500000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,2574.02500000
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,3861.15000000
        ///14,39,12871,12873.75,12869.5,12872.75,333,5148.42500000
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,6435.47500000
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,7722.05000000
        ///14,42,12866,12870.75,12866,12870.25,374,9009.07500000
        ///14,43,12869.5,12883,12869.5,12877.25,1369,10296.80000000
        ///14,44,12877.75,12878.25,12866.25,12868.75,10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmaaBaseline {
            get {
                return ResourceManager.GetString("SmaaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,12870.12500000
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,12870.50000000
        ///14,39,12871,12873.75,12869.5,12872.75,333,12871.06250000
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,12870.95000000
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,12870.08333333
        ///14,42,12866,12870.75,12866,12870.25,374,12870.10714286
        ///14,43,12869.5,12883,12869.5,12877.25,1369,12871.00000000
        ///14,44,12877.75,12878.25,12866.25,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmaBaseline {
            get {
                return ResourceManager.GetString("SmaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866.00,12870.75,1068,00.00000000
        ///14,37,12871.25,12871.50,12864.75,12869.50,0427,00.62500000
        ///14,38,12869.25,12871.75,12867.50,12871.25,0414,00.73598007
        ///14,39,12871.00,12873.75,12869.50,12872.75,0333,01.16424600
        ///14,40,12872.75,12873.75,12867.75,12870.50,0378,01.06536379
        ///14,41,12870.25,12872.25,12864.50,12865.75,0601,02.16826864
        ///14,42,12866.00,12870.75,12866.00,12870.25,0374,02.00827370
        ///14,43,12869.50,12883.00,12869.50,12877.25,1369,03.01817412
        ///14,44,12877.75,12878.25,12866.25 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdDevBaseline {
            get {
                return ResourceManager.GetString("StdDevBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/1/2020 9:31:00 AM,12375.5,12383.75,12365.75,12365.75,0,0
        ///12/1/2020 9:32:00 AM,12365.75,12369.25,12359.25,12364.5,10.7142857142857,5.35714285714286
        ///12/1/2020 9:33:00 AM,12364.5,12367,12360.75,12361,9.52380952380952,6.74603174603175
        ///12/1/2020 9:34:00 AM,12361.25,12363.75,12351,12351.75,10.2871683024355,7.63131588513268
        ///12/1/2020 9:35:00 AM,12351.5,12351.75,12337.5,12344.25,8.0091760244432,7.70688791299478
        ///12/1/2020 9:36:00 AM,12344,12347.5,12336.75,12344.75,11.301982508739,8.30607034561883
        ///12/1/2020  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StochasticsBaseline {
            get {
                return ResourceManager.GetString("StochasticsBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,12870.18463561
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,12870.60270815
        ///14,39,12871,12873.75,12869.5,12872.75,333,12871.56631595
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,12871.18648737
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,12868.77300221
        ///14,42,12866,12870.75,12866,12870.25,374,12869.20755959
        ///14,43,12869.5,12883,12869.5,12877.25,1369,12872.69332198
        ///14,44,12877.75,12878.25,12866.25,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemaBaseline {
            get {
                return ResourceManager.GetString("TemaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,1068,12870.75000000
        ///14,37,12871.25,12871.5,12864.75,12869.5,427,12869.91666667
        ///14,38,12869.25,12871.75,12867.5,12871.25,414,12870.58333333
        ///14,39,12871,12873.75,12869.5,12872.75,333,12871.45000000
        ///14,40,12872.75,12873.75,12867.75,12870.5,378,12871.13333333
        ///14,41,12870.25,12872.25,12864.5,12865.75,601,12869.59523810
        ///14,42,12866,12870.75,12866,12870.25,374,12869.75892857
        ///14,43,12869.5,12883,12869.5,12877.25,1369,12871.42361111
        ///14,44,12877.75,12878.25,12866.25,1286 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WmaBaseline {
            get {
                return ResourceManager.GetString("WmaBaseline", resourceCulture);
            }
        }
    }
}
