//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Baselines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Baselines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.Baselines", typeof(Baselines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,7.75
        ///14,37,12871.25,12871.5,12864.75,12869.5,7.25
        ///14,38,12869.25,12871.75,12867.5,12871.25,6.25
        ///14,39,12871,12873.75,12869.5,12872.75,5.75
        ///14,40,12872.75,12873.75,12867.75,12870.5,5.8
        ///14,41,12870.25,12872.25,12864.5,12865.75,6.125
        ///14,42,12866,12870.75,12866,12870.25,5.96428571
        ///14,43,12869.5,12883,12869.5,12877.25,6.90625
        ///14,44,12877.75,12878.25,12866.25,12868.75,7.47222222
        ///14,45,12869.25,12870.75,12861,12867.5,7.7
        ///14,46,12867.25,12872,12865.5,12866,7.58
        ///14,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtrBaseline {
            get {
                return ResourceManager.GetString("AtrBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,12870.75,12870.75,12870.75
        ///14,37,12871.25,12871.5,12864.75,12869.5,12871.375,12870.125,12868.875
        ///14,38,12869.25,12871.75,12867.5,12871.25,12871.97196,12870.5,12869.02804
        ///14,39,12871,12873.75,12869.5,12872.75,12873.39099,12871.0625,12868.73401
        ///14,40,12872.75,12873.75,12867.75,12870.5,12873.08073,12870.95,12868.81927
        ///14,41,12870.25,12872.25,12864.5,12865.75,12874.41987,12870.08333,12865.7468
        ///14,42,12866,12870.75,12866,12870.25,12874.12369,12870.10714,12866.0906
        ///14 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BollingerBandsBaseline {
            get {
                return ResourceManager.GetString("BollingerBandsBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12860.25,12860.5,12853.75,12858.5,0
        ///14,37,12858.25,12860.75,12856.5,12860.25,66.66666667
        ///14,38,12860,12862.75,12858.5,12861.75,100
        ///14,39,12861.75,12862.75,12856.75,12859.5,21.27659574
        ///14,40,12859.25,12861.25,12853.5,12854.75,-109.2503987
        ///14,41,12855,12859.75,12855,12859.25,-33.69175627
        ///14,42,12858.5,12872,12858.5,12866.25,189.3224932
        ///14,43,12866.75,12867.25,12855.25,12857.75,13.57175608
        ///14,44,12858.25,12859.75,12850,12856.5,-120.8823529
        ///14,45,12856.25,12861,12854.5,12855,-67.71653543
        ///14,46,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CciBaseline {
            get {
                return ResourceManager.GetString("CciBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,12870.75
        ///14,37,12871.25,12871.5,12864.75,12869.5,12869.5
        ///14,38,12869.25,12871.75,12867.5,12871.25,12871.25
        ///14,39,12871,12873.75,12869.5,12872.75,12872.75
        ///14,40,12872.75,12873.75,12867.75,12870.5,12870.5
        ///14,41,12870.25,12872.25,12864.5,12865.75,12865.75
        ///14,42,12866,12870.75,12866,12870.25,12870.25
        ///14,43,12869.5,12883,12869.5,12877.25,12877.25
        ///14,44,12877.75,12878.25,12866.25,12868.75,12868.75
        ///14,45,12869.25,12870.75,12861,12867.5,12867.5
        ///14,46,12867.25,12872,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KamaBaseline {
            get {
                return ResourceManager.GetString("KamaBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12860.25,12860.5,12853.75,12858.5,12867.70833,12857.58333,12847.45833
        ///14,37,12858.25,12860.75,12856.5,12860.25,12866.625,12858.375,12850.125
        ///14,38,12860,12862.75,12858.5,12861.75,12866.875,12859.25,12851.625
        ///14,39,12861.75,12862.75,12856.75,12859.5,12867.32292,12859.35417,12851.38542
        ///14,40,12859.25,12861.25,12853.5,12854.75,12867.48333,12858.78333,12850.08333
        ///14,41,12855,12859.75,12855,12859.25,12867.09028,12858.65278,12850.21528
        ///14,42,12858.5,12872,12858.5,12866.25,12869.76786,12859.64286,12849 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeltnerChannelBaseline {
            get {
                return ResourceManager.GetString("KeltnerChannelBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,0,0,0
        ///14,37,12871.25,12871.5,12864.75,12869.5,-0.07102273,-0.03551136,-0.03551136
        ///14,38,12869.25,12871.75,12867.5,12871.25,-0.02082257,-0.02816697,0.0073444
        ///14,39,12871,12873.75,12869.5,12872.75,0.10081669,0.03632486,0.06449183
        ///14,40,12872.75,12873.75,12867.75,12870.5,0.05776714,0.047046,0.01072114
        ///14,41,12870.25,12872.25,12864.5,12865.75,-0.24425167,-0.09860283,-0.14564884
        ///14,42,12866,12870.75,12866,12870.25,-0.19923669,-0.14891976,-0.05031693
        ///14,43,12869.5,128 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MacdBaseline {
            get {
                return ResourceManager.GetString("MacdBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,36,12872.75,12873.75,12866,12870.75,0,0
        ///14,37,12871.25,12871.5,12864.75,12869.5,0,0
        ///14,38,12869.25,12871.75,12867.5,12871.25,0,0
        ///14,39,12871,12873.75,12869.5,12872.75,0,0
        ///14,40,12872.75,12873.75,12867.75,12870.5,0,0
        ///14,41,12870.25,12872.25,12864.5,12865.75,0,0
        ///14,42,12866,12870.75,12866,12870.25,0,0
        ///14,43,12869.5,12883,12869.5,12877.25,0,0
        ///14,44,12877.75,12878.25,12866.25,12868.75,0,50
        ///14,45,12869.25,12870.75,12861,12867.5,45.03816794,47.51908397
        ///14,46,12867.25,12872,12865.5,12866,42.85714286,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsiBaseline {
            get {
                return ResourceManager.GetString("RsiBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/1/2020 9:31:00 AM,12375.5,12383.75,12365.75,12365.75,0,0
        ///12/1/2020 9:32:00 AM,12365.75,12369.25,12359.25,12364.5,10.7142857142857,5.35714285714286
        ///12/1/2020 9:33:00 AM,12364.5,12367,12360.75,12361,9.52380952380952,6.74603174603175
        ///12/1/2020 9:34:00 AM,12361.25,12363.75,12351,12351.75,10.2871683024355,7.63131588513268
        ///12/1/2020 9:35:00 AM,12351.5,12351.75,12337.5,12344.25,8.0091760244432,7.70688791299478
        ///12/1/2020 9:36:00 AM,12344,12347.5,12336.75,12344.75,11.301982508739,8.30607034561883
        ///12/1/2020  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StochasticsBaseline {
            get {
                return ResourceManager.GetString("StochasticsBaseline", resourceCulture);
            }
        }
    }
}
